# Generated by Django 4.1.6 on 2023-02-11 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='data',
            field=models.CharField(default='1gb', max_length=255),
        ),
        migrations.AddField(
            model_name='plan',
            name='is_unlimited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plan',
            name='message',
            field=models.CharField(default='100 Messages', max_length=255),
        ),
    ]
